# Jekyll configuration

name: Adam Hoke
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://adamhoke.com
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: 

social:
  github: adamhoke
  stackoverflow: 'adamhoke'
  linkedin:
  twitter: 'adamhoke'
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:

disqus: adamhoke
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
