title: Adam Hoke
description: IT, web, software, and security blog
author: Adam Hoke
github: https://github.com/adamhoke
about: I am a programmer and web developer. Currently working on cloud-base web applications.
disqus_shortname: adamhoke
google_analytics: UA-XXXXXXXX-Y
avatar_url:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/adamhoke"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/adamhoke"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/adamhoke"

share:
  twitter_username: adamhoke

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "http://adamhoke.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
